version: "3"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql-data:/var/lib/mysql
  app1:
    image: backend
    ports:
      - 3001:3001
    volumes:
      - ./:/src/src/app
    environment:
      - PORT=3001
volumes:
  mysql-data:
