version: "3"

services:
  nginx:
    image: nginx
    ports:
      - "3001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  redis:
    image: redis
    ports:
      - 6379:6379
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql-data:/var/lib/mysql
  app1:
    image: backendauth
    environment:
      - PORT=1111
  app2:
    image: backendauth
    environment:
      - PORT=2222

volumes:
  mysql-data:
